FEAT-TaskModelUpdate
rubykap30/cs490-team10 pull request #69
Opened 2023-11-23 21:44 UTC by jameslpineda

This PR adds completed_timers and finish_at attributes to the task model.

2023-11-23 23:43 UTC, rubykap30 requested changes

2023-11-23 23:43 UTC, rubykap30 commented on app/api/src/validations/taskValidation.ts
> -    user_id: Joi.string().required(),
wait james, why are we removing date, user_id, and _id from the create Task validation -> this is going to throw off abdul's front end create task service

2023-11-23 23:43 UTC, rubykap30 commented on app/api/src/controllers/taskController.ts
i think @jasonzheng32 only needs the completed_timers because the finish_at is not persistent and just calculated on the frontend when timer is started

2023-11-24 03:03 UTC, jameslpineda commented on app/api/src/controllers/taskController.ts
From what I was reading in the requirements, it sounds like it is something that needs to be set and can be revisited when you leave the task and come back. I feel like this makes the most sense right?

2023-11-24 03:24 UTC, rubykap30 commented on app/api/src/controllers/taskController.ts
he clarified that the finished time can Just make it for the single pomo timer being completed.

there really isn't too big of an issue having it on the backend, but it is a useless attribute since there is no point of updating it since it can fully be calculated on the frontend

2023-11-28 04:41 UTC, rubykap30 approved these changes
looks great!

2023-11-28 04:47 UTC, merged